Dz1
VasilevichDev/HomeWork pull request #1
Opened 2021-04-12 19:14 UTC by VasilevichDev

DZ 1

2021-04-13 11:35 UTC, YudjinFoggy approved these changes

2021-04-13 12:23 UTC, YarikGuk approved these changes

2021-04-13 12:38 UTC, Berikz80 requested changes
make check for empty string textUrl

2021-04-13 12:38 UTC, Berikz80 commented on app/src/main/java/com/example/homework/PictureActivity.kt
> +            Picasso.get().load(textUrl).into(picture)
exception if you get empty textUrl

2021-04-13 17:21 UTC, VasilevichDev commented on app/src/main/java/com/example/homework/PictureActivity.kt
> +            Picasso.get().load(textUrl).into(picture)
fixed)

2021-04-13 20:32 UTC, Berikz80 approved these changes
good job

2021-04-14 09:29 UTC, e-kleban approved these changes

2021-04-14 21:01 UTC, Gizcerbes approved these changes

2021-04-15 10:36 UTC, TMSlebedev approved these changes

2021-04-19 15:40 UTC, merged